[2025-04-29T14:42:00.385-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-29T14:42:00.391-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: entrenamiento.extractionData manual__2025-04-29T19:41:57.760503+00:00 [queued]>
[2025-04-29T14:42:00.394-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: entrenamiento.extractionData manual__2025-04-29T19:41:57.760503+00:00 [queued]>
[2025-04-29T14:42:00.394-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-29T14:42:00.408-0500] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): extractionData> on 2025-04-29 19:41:57.760503+00:00
[2025-04-29T14:42:00.413-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'entrenamiento', 'extractionData', 'manual__2025-04-29T19:41:57.760503+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/train.py', '--cfg-path', '/tmp/tmp2ydiav6h']
[2025-04-29T14:42:00.415-0500] {standard_task_runner.py:105} INFO - Job 18: Subtask extractionData
[2025-04-29T14:42:00.416-0500] {logging_mixin.py:190} WARNING - /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=55695) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-29T14:42:00.416-0500] {standard_task_runner.py:72} INFO - Started process 55727 to run task
[2025-04-29T14:42:00.444-0500] {task_command.py:467} INFO - Running <TaskInstance: entrenamiento.extractionData manual__2025-04-29T19:41:57.760503+00:00 [running]> on host DESKTOP-0R7MK50.
[2025-04-29T14:42:00.492-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='entrenamiento' AIRFLOW_CTX_TASK_ID='extractionData' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T19:41:57.760503+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T19:41:57.760503+00:00'
[2025-04-29T14:42:00.493-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-29T14:42:02.476-0500] {logging_mixin.py:190} WARNING - /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/urllib3/connectionpool.py:1097 InsecureRequestWarning: Unverified HTTPS request is being made to host 'auth.iqoption.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-04-29T14:42:16.399-0500] {python.py:240} INFO - Done. Returned value was: Data Almacenada
[2025-04-29T14:42:16.422-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-29T14:42:16.422-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=entrenamiento, task_id=extractionData, run_id=manual__2025-04-29T19:41:57.760503+00:00, execution_date=20250429T194157, start_date=20250429T194200, end_date=20250429T194216
[2025-04-29T14:42:16.463-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-29T14:42:16.472-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-29T14:42:16.481-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
