[2025-05-07T19:30:02.294-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-07T19:30:02.299-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: request_operation.RealtimeData scheduled__2025-05-08T00:29:20+00:00 [queued]>
[2025-05-07T19:30:02.302-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: request_operation.RealtimeData scheduled__2025-05-08T00:29:20+00:00 [queued]>
[2025-05-07T19:30:02.302-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-05-07T19:30:02.315-0500] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): RealtimeData> on 2025-05-08 00:29:20+00:00
[2025-05-07T19:30:02.320-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'request_operation', 'RealtimeData', 'scheduled__2025-05-08T00:29:20+00:00', '--job-id', '412', '--raw', '--subdir', 'DAGS_FOLDER/operations.py', '--cfg-path', '/tmp/tmpscq1wfeb']
[2025-05-07T19:30:02.321-0500] {standard_task_runner.py:105} INFO - Job 412: Subtask RealtimeData
[2025-05-07T19:30:02.322-0500] {logging_mixin.py:190} WARNING - /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=68146) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-07T19:30:02.323-0500] {standard_task_runner.py:72} INFO - Started process 68171 to run task
[2025-05-07T19:30:02.351-0500] {task_command.py:467} INFO - Running <TaskInstance: request_operation.RealtimeData scheduled__2025-05-08T00:29:20+00:00 [running]> on host DESKTOP-0R7MK50.
[2025-05-07T19:30:02.418-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='request_operation' AIRFLOW_CTX_TASK_ID='RealtimeData' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T00:29:20+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-08T00:29:20+00:00'
[2025-05-07T19:30:02.418-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-07T19:30:18.757-0500] {logging_mixin.py:190} WARNING - /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/urllib3/connectionpool.py:1097 InsecureRequestWarning: Unverified HTTPS request is being made to host 'auth.iqoption.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-05-07T19:30:18.983-0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/iqoptions_bot/dags/operations.py", line 18, in RealtimeData
    API = ConectionApi(gmail=gmail, password=password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/iqoptions_bot/dags/utils/extraction.py", line 21, in __init__
    self.API.connect()
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/stable_api.py", line 103, in connect
    check, reason = self.api.connect()
                    ^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/api.py", line 872, in connect
    self.send_ssid()
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/api.py", line 825, in send_ssid
    self.ssid(global_value.SSID)  # pylint: disable=not-callable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/ws/chanels/ssid.py", line 17, in __call__
    self.send_websocket_request(self.name, ssid)
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/ws/chanels/base.py", line 25, in send_websocket_request
    return self.api.send_websocket_request(name, msg,request_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/api.py", line 277, in send_websocket_request
    self.websocket.send(data)
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/websocket/_app.py", line 154, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
[2025-05-07T19:30:18.987-0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=request_operation, task_id=RealtimeData, run_id=scheduled__2025-05-08T00:29:20+00:00, execution_date=20250508T002920, start_date=20250508T003002, end_date=20250508T003018
[2025-05-07T19:30:19.012-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-07T19:30:19.013-0500] {standard_task_runner.py:124} ERROR - Failed to execute job 412 for task RealtimeData (Connection is already closed.; 68171)
Traceback (most recent call last):
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/iqoptions_bot/dags/operations.py", line 18, in RealtimeData
    API = ConectionApi(gmail=gmail, password=password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/iqoptions_bot/dags/utils/extraction.py", line 21, in __init__
    self.API.connect()
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/stable_api.py", line 103, in connect
    check, reason = self.api.connect()
                    ^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/api.py", line 872, in connect
    self.send_ssid()
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/api.py", line 825, in send_ssid
    self.ssid(global_value.SSID)  # pylint: disable=not-callable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/ws/chanels/ssid.py", line 17, in __call__
    self.send_websocket_request(self.name, ssid)
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/ws/chanels/base.py", line 25, in send_websocket_request
    return self.api.send_websocket_request(name, msg,request_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/api.py", line 277, in send_websocket_request
    self.websocket.send(data)
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/websocket/_app.py", line 154, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
[2025-05-07T19:30:19.047-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-07T19:30:19.056-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-07T19:30:19.067-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
